### ISSUE TITLE
Anonymous users get no feedback when clicking "Giv assist" 

### ISSUE THREAD

**Issue by cfdp** [magenta-aps/myassist#3]
When an anonymous user tries to upvote he is redirected to a page (https://mitassist.dk/da/user/login-to-rate?destination=node/1343 ), telling him he needs to create a user before he can vote.

Same feature should be created for the "Giv assist" button.

**Comment by benjamin-dk** [comment]
@stefanospetrakis theres a small thing that needs correction: when you’re anonymous and on the front page and click on the “Læs mere her” button (Read more) - with your fix you are redirected to the login page. There should be no redirect - it should be possible to go to the full node view as anonymous user

**Comment by stefanospetrakis** [comment]
Just posted an update that should handle this case, thanks for the feedback @benjamin-dk

**Comment by benjamin-dk** [comment]
Fixed in 699c1c09
